### ISSUE TITLE
what makes use of the userrepository class?

### ISSUE THREAD

**Issue by jummy0** [PHSCDC/itocdc-2016-www#6]
in `getUserByUsername`, all fields of a user are selected, including the password. this seems like a security flaw; is this necessary?

**Comment by ngiddings** [comment]
First and foremost, MainController.java makes use of the user repo quite a bit. MainController basically contains a bunch of server-side code for the site. It queries user information quite a bit, naturally. I noticed that the complete user list is queried to generate the /admin page, but not all information is actually needed. Take a look:

``` Java
    @RequestMapping("/admin")
    public String admin(ModelMap modelMap) {
        List<User> userList = userRepository.getAllUsers();
        modelMap.put("users", userList);

        List<String> unApprovedImages = imageRepository.getUnApprovedImages();
        List<String> imageList = getImageNames(unApprovedImages);
        modelMap.put("images", imageList);

        return "admin";
    }
```

The only information I can see actually displayed is the username; we certainly need to rework the user repo so that queries can be securely and cleanly limited to only required information. Any ideas on how?

**Comment by ngiddings** [comment]
Also, passwords being stored in plaintext is an issue itself. As far as I can tell, this app can be adapted to not expect plaintext passwords. The admin panel has a function to change passwords, but does not display them. Therefore, a write-only scheme for storing passwords should be fine. I'll make a forum post about getting this change made; we should discuss the adaptations that needs to be made here.

**Comment by ngiddings** [comment]
Added issue #9 regarding plaintext passwords.

**Comment by ngiddings** [comment]
Added issue #10 regarding limiting the information UserRepository must query.

**Comment by ngiddings** [comment]
A related question: is there anything in the app that actually uses the queried password?

**Comment by ngiddings** [comment]
This class wraps all DB access to the user table. It makes use of related utilities to read User objects from an SQL table. So for the most part only controllers use it.
